#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am243x libs
	$(MAKE) -f makefile.am243x sbl
	$(MAKE) -f makefile.am243x examples


clean: libs-clean sbl-clean examples-clean
scrub: libs-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am243x help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am243x all
	@echo  $(MAKE) -s -f makefile.am243x clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am243x scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am243x libs
	@echo  $(MAKE) -s -f makefile.am243x libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am243x libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am243x examples
	@echo  $(MAKE) -s -f makefile.am243x examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am243x examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-evm/icss_g0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-evm/icss_g0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-lp/icss_g0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-evm/icss_g0_rtu_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-evm/icss_g0_rtu_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-lp/icss_g0_rtu_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-evm/icss_g0_tx_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-lp/icss_g0_tx_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-evm/icss_g0_tx_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am243x-lp/icss_g0_tx_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am243x-evm/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am243x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_rtu_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_rtu_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_rtu_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_tx_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_tx_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_tx_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_tx_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/am243x-evm/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/am243x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets


# Combine all Components
BUILD_COMBO_ALL =


# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =


# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)




# Various Component Clean Targets


# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL =


# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =


libs-clean: $(BUILD_COMBO_CLEAN_ALL)
libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)




# Various Component Scrub Targets


# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL =

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =


libs-scrub: $(BUILD_COMBO_SCRUB_ALL)
libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)



BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_ALL += empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang

# Various System Example Targets



BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets


examples: $(BUILD_COMBO_EXAMPLE_ALL)



examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile all

 empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/empty/am243x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile all

 empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/empty/am243x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile all

 empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile all

 empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile all

 empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/gpio_toggle/am243x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile all

 empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/gpio_toggle/am243x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang_clean
# Various System Example Clean Targets


BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile clean

 empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/empty/am243x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/empty/am243x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile clean

 empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/gpio_toggle/am243x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/gpio_toggle/am243x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
# Various System Example Scrub Targets


BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-evm/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am243x-lp/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/empty/am243x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/empty/am243x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 empty_am243x-evm_icss_g0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_rtu_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_rtu_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_rtu_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_rtu_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_rtu_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_tx_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_tx_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_tx_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-evm_icss_g0_tx_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-evm/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am243x-lp_icss_g0_tx_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am243x-lp/icss_g0_tx_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_pru_io_am243x-evm_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/gpio_toggle/am243x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 empty_pru_io_am243x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/gpio_toggle/am243x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:




.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)