#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am261x libs
	$(MAKE) -f makefile.am261x sbl
	$(MAKE) -f makefile.am261x examples


clean: libs-clean sbl-clean examples-clean
scrub: libs-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am261x help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am261x all
	@echo  $(MAKE) -s -f makefile.am261x clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am261x scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am261x libs
	@echo  $(MAKE) -s -f makefile.am261x libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am261x libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am261x examples
	@echo  $(MAKE) -s -f makefile.am261x examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am261x examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C examples/empty/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am261x-som/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am261x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/gpio/gpio_toggle/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/gpio/gpio_toggle/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/gpio/gpio_toggle/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/gpio/gpio_toggle/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/gpio/gpio_toggle/am261x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/intc/intc_mcu/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/intc/intc_mcu/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/intc/intc_mcu/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/intc/intc_mcu/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/intc/intc_mcu/am261x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac/am261x-som/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac/am261x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac_multiply/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac_multiply/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac_multiply/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac_multiply/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac_multiply/am261x-som/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/mac/mac_multiply/am261x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/crc/crc/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/crc/crc/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/crc/crc/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/crc/crc/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/crc/crc/am261x-som/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C academy/crc/crc/am261x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/fft/split_radix_fft_4k_single_core/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets


# Combine all Components
BUILD_COMBO_ALL =


# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =


# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)




# Various Component Clean Targets


# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL =


# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =


libs-clean: $(BUILD_COMBO_CLEAN_ALL)
libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)




# Various Component Scrub Targets


# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL =

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =


libs-scrub: $(BUILD_COMBO_SCRUB_ALL)
libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)



BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets

# Various System Example Targets



BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_am261x-som_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_am261x-som_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_toggle_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_toggle_am261x-som_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_toggle_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_toggle_am261x-som_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_mcu_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_mcu_am261x-som_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_mcu_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_mcu_am261x-som_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_am261x-som_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_am261x-som_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_am261x-som_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_am261x-som_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_am261x-som_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_am261x-som_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += split_radix_fft_4k_single_core_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt
# Various Private System Example Targets


examples: $(BUILD_COMBO_EXAMPLE_ALL)



examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 empty_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 empty_am261x-som_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 empty_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 empty_am261x-som_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 empty_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/empty/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile all

 empty_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/empty/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 gpio_toggle_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 gpio_toggle_am261x-som_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 gpio_toggle_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 gpio_toggle_am261x-som_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 gpio_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C academy/gpio/gpio_toggle/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 intc_mcu_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 intc_mcu_am261x-som_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 intc_mcu_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 intc_mcu_am261x-som_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 intc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C academy/intc/intc_mcu/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 mac_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/mac/mac/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 mac_am261x-som_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/mac/mac/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 mac_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/mac/mac/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 mac_am261x-som_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/mac/mac/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 mac_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C academy/mac/mac/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile all

 mac_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C academy/mac/mac/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 mac_multiply_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 mac_multiply_am261x-som_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 mac_multiply_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 mac_multiply_am261x-som_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 mac_multiply_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C academy/mac/mac_multiply/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile all

 mac_multiply_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C academy/mac/mac_multiply/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 crc_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/crc/crc/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 crc_am261x-som_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C academy/crc/crc/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 crc_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/crc/crc/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 crc_am261x-som_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C academy/crc/crc/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 crc_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C academy/crc/crc/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile all

 crc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C academy/crc/crc/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 split_radix_fft_4k_single_core_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/fft/split_radix_fft_4k_single_core/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
# Various System Example Clean Targets


BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_toggle_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_toggle_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_toggle_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_toggle_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_mcu_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_mcu_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_mcu_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_mcu_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += split_radix_fft_4k_single_core_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 empty_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 empty_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/empty/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 empty_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/empty/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 gpio_toggle_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 gpio_toggle_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 gpio_toggle_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 gpio_toggle_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 gpio_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C academy/gpio/gpio_toggle/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 intc_mcu_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 intc_mcu_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 intc_mcu_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 intc_mcu_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 intc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C academy/intc/intc_mcu/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 mac_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/mac/mac/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 mac_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/mac/mac/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 mac_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/mac/mac/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 mac_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/mac/mac/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 mac_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C academy/mac/mac/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 mac_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C academy/mac/mac/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 mac_multiply_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 mac_multiply_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 mac_multiply_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 mac_multiply_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 mac_multiply_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C academy/mac/mac_multiply/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 mac_multiply_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C academy/mac/mac_multiply/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 crc_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/crc/crc/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 crc_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/crc/crc/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 crc_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/crc/crc/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 crc_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C academy/crc/crc/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 crc_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C academy/crc/crc/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 crc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C academy/crc/crc/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 split_radix_fft_4k_single_core_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/fft/split_radix_fft_4k_single_core/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
# Various System Example Scrub Targets


BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_toggle_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_toggle_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_toggle_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_toggle_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_mcu_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_mcu_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_mcu_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_mcu_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += split_radix_fft_4k_single_core_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 empty_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/empty/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 empty_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/empty/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 gpio_toggle_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 gpio_toggle_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 gpio_toggle_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 gpio_toggle_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/gpio/gpio_toggle/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 gpio_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C academy/gpio/gpio_toggle/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 intc_mcu_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 intc_mcu_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 intc_mcu_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 intc_mcu_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/intc/intc_mcu/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 intc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C academy/intc/intc_mcu/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 mac_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/mac/mac/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 mac_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/mac/mac/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 mac_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/mac/mac/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 mac_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/mac/mac/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 mac_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C academy/mac/mac/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 mac_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C academy/mac/mac/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 mac_multiply_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 mac_multiply_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 mac_multiply_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 mac_multiply_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/mac/mac_multiply/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 mac_multiply_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C academy/mac/mac_multiply/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 mac_multiply_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C academy/mac/mac_multiply/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 crc_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/crc/crc/firmware/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 crc_am261x-som_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/crc/crc/firmware/am261x-som/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 crc_am261x-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/crc/crc/firmware/am261x-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 crc_am261x-som_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C academy/crc/crc/firmware/am261x-som/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 crc_pru_io_am261x-som_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C academy/crc/crc/am261x-som/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 crc_pru_io_am261x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C academy/crc/crc/am261x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 split_radix_fft_4k_single_core_am261x-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/fft/split_radix_fft_4k_single_core/am261x-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:




.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)