#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am263px libs
	$(MAKE) -f makefile.am263px sbl
	$(MAKE) -f makefile.am263px examples


clean: libs-clean sbl-clean examples-clean
scrub: libs-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px all
	@echo  $(MAKE) -s -f makefile.am263px clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px libs
	@echo  $(MAKE) -s -f makefile.am263px libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px examples
	@echo  $(MAKE) -s -f makefile.am263px examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C examples/empty/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/empty/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/gpio_toggle/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/intc_sys_event/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/intc_sys_event/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/intc_sys_event/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/intc_sys_event/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/intc_sys_event/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/intc_sys_event/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac_multiply/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac_multiply/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac_multiply/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac_multiply/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac_multiply/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/mac_multiply/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/crc/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/crc/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/crc/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/crc/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/crc/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/crc/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets


# Combine all Components
BUILD_COMBO_ALL =


# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =


# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)




# Various Component Clean Targets


# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL =


# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =


libs-clean: $(BUILD_COMBO_CLEAN_ALL)
libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)




# Various Component Scrub Targets


# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL =

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =


libs-scrub: $(BUILD_COMBO_SCRUB_ALL)
libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)



BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets

# Various System Example Targets



BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += empty_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_toggle_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_toggle_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_toggle_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_toggle_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += gpio_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_sys_event_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_sys_event_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_sys_event_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_sys_event_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += intc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += mac_multiply_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += crc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang
# Various Private System Example Targets


examples: $(BUILD_COMBO_EXAMPLE_ALL)



examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 empty_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 empty_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 empty_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 empty_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/empty/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 empty_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/empty/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 empty_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/empty/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 gpio_toggle_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 gpio_toggle_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 gpio_toggle_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 gpio_toggle_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 gpio_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/gpio_toggle/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 intc_sys_event_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 intc_sys_event_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 intc_sys_event_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 intc_sys_event_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 intc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/intc_sys_event/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 intc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/intc_sys_event/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 mac_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/mac/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 mac_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/mac/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 mac_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/mac/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 mac_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/mac/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 mac_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/mac/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 mac_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/mac/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 mac_multiply_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 mac_multiply_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 mac_multiply_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 mac_multiply_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 mac_multiply_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/mac_multiply/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 mac_multiply_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/mac_multiply/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 crc_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/crc/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 crc_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C examples/crc/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 crc_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/crc/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 crc_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C examples/crc/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 crc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/crc/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 crc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/crc/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
# Various System Example Clean Targets


BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += empty_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_toggle_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_toggle_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_toggle_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_toggle_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += gpio_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_sys_event_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_sys_event_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_sys_event_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_sys_event_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += intc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += mac_multiply_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += crc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 empty_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 empty_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 empty_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/empty/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 empty_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/empty/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 empty_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/empty/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 gpio_toggle_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 gpio_toggle_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 gpio_toggle_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 gpio_toggle_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 gpio_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/gpio_toggle/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 intc_sys_event_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 intc_sys_event_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 intc_sys_event_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 intc_sys_event_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 intc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/intc_sys_event/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 intc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/intc_sys_event/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 mac_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/mac/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 mac_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/mac/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 mac_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/mac/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 mac_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/mac/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 mac_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/mac/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 mac_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/mac/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 mac_multiply_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 mac_multiply_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 mac_multiply_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 mac_multiply_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 mac_multiply_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/mac_multiply/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 mac_multiply_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/mac_multiply/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 crc_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/crc/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 crc_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/crc/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 crc_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/crc/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 crc_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C examples/crc/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 crc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/crc/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 crc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/crc/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
# Various System Example Scrub Targets


BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += empty_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_toggle_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_toggle_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_toggle_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_toggle_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += gpio_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_sys_event_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_sys_event_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_sys_event_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_sys_event_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += intc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += mac_multiply_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += crc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 empty_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 empty_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/empty/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 empty_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/empty/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 empty_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/empty/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 gpio_toggle_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 gpio_toggle_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 gpio_toggle_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 gpio_toggle_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/gpio_toggle/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 gpio_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/gpio_toggle/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 intc_sys_event_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 intc_sys_event_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 intc_sys_event_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 intc_sys_event_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/intc_sys_event/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 intc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/intc_sys_event/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 intc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/intc_sys_event/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 mac_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/mac/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 mac_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/mac/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 mac_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/mac/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 mac_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/mac/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 mac_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/mac/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 mac_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/mac/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 mac_multiply_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 mac_multiply_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 mac_multiply_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 mac_multiply_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/mac_multiply/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 mac_multiply_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/mac_multiply/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 mac_multiply_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/mac_multiply/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 crc_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/crc/firmware/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 crc_am263px-cc_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/crc/firmware/am263px-cc/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 crc_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/crc/firmware/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 crc_am263px-cc_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C examples/crc/firmware/am263px-cc/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 crc_pru_io_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/crc/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 crc_pru_io_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/crc/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:




.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)